spring:
  application:
    name: jibmusil
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
    
  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/jibmusil_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 20000
      
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        
  # Redis Configuration
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 50
          max-idle: 20
          min-idle: 5
          max-wait: 3000ms
          
  # Elasticsearch Configuration
  elasticsearch:
    uris: http://${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}
    connection-timeout: 1s
    socket-timeout: 30s
    
  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: jibmusil-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      
  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 600000  # 10 minutes
      
  # Batch Configuration
  batch:
    jdbc:
      initialize-schema: always

  # AI Configuration
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      chat:
        options:
          model: gpt-4
          temperature: 0.7

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
      
# Logging Configuration
logging:
  level:
    com.example.jibmusil: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}
    org.springframework.kafka: ${KAFKA_LOG_LEVEL:INFO}
    org.elasticsearch: ${ELASTICSEARCH_LOG_LEVEL:INFO}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/jibmusil.log
    
# External API Configuration
newsapi:
  key: ${NEWSAPI_KEY:c81a2db6fc25447b8565298746d48fbc}
  base-url: ${NEWSAPI_BASE_URL:https://newsapi.org/v2}
  rate-limit:
    requests-per-hour: 1000
    
# Security Configuration
jwt:
  secret: ${JWT_SECRET:your-very-secure-secret-key-that-should-be-at-least-256-bits-long}
  expiration: ${JWT_EXPIRATION:86400000}  # 1 day in ms
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days in ms


# Custom Application Configuration
jibmusil:
  news:
    fetch-interval: ${NEWS_FETCH_INTERVAL:300000}  # 5 minutes
    batch-size: ${NEWS_BATCH_SIZE:100}
    max-articles-per-source: ${MAX_ARTICLES_PER_SOURCE:50}
  recommendation:
    model-update-interval: ${MODEL_UPDATE_INTERVAL:3600000}  # 1 hour
    max-recommendations: ${MAX_RECOMMENDATIONS:20}
  email:
    daily-digest-time: ${DAILY_DIGEST_TIME:08:00}
    weekly-digest-day: ${WEEKLY_DIGEST_DAY:MONDAY}
  analytics:
    retention-days: ${ANALYTICS_RETENTION_DAYS:90}
    
---
# Docker Profile
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://mysql:3306/jibmusil_db?useSSL=false&serverTimezone=UTC
    username: jibmusil
    password: jibmusil123
  data:
    redis:
      host: redis
      port: 6379
  elasticsearch:
    uris: http://elasticsearch:9200
  kafka:
    bootstrap-servers: kafka:9092
    
logging:
  level:
    com.example.jibmusil: INFO
    org.springframework.security: WARN